version: '3.9'
services:
  api:
    build: ./backend
    environment:
      - PORT=4000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET:-change_me_access}
      - CORS_ORIGIN=http://localhost:3000
    ports:
      - "4000:4000"
  web:
    build: ./frontend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - api
